<?php

/**
 * @file
 * Contains acme_sports_nfl_teams.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function acme_sports_nfl_teams_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the acme_sports_nfl_teams module.
    case 'help.page.acme_sports_nfl_teams':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A module that provides integration with formulary API&#039;&#039;s') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function acme_sports_nfl_teams_theme($existing, $type, $theme, $path) {

  // For the results returned from NFL Api.
  $themes['acme_sports_nfl_teams_results'] = [
    'template' => 'bi-formulary-results',
    'variables' => [
      'no_results' => NULL,
      'error' => NULL,
      'download_link' => NULL,
    ],
    'file' => 'acme_sports_nfl_teams.theme.inc',
  ];

  return $themes;
}
